.\" Manpage for vsnm.
.\" Contact dmelo87@gmail.com to correct errors or typos.
.TH man 8 "24 Jul 2012" "0.1" "vsnm man page"
.SH NAME
vsnm \- Very Simple Network Manager
.SH SYNOPSIS
vsnm
.SH DESCRIPTION
vsnm is a network manager for wireless networks. It aims for simplicity. All known networks should be listed on the /etc/vsnm.cfg file. vsnm will scan all available networks and connect to the first found on the /etc/vsnm.cfg. vsnm is not a daemon. Once the connection is made, the execution is over and no other change is performed. It is advised to turn off/disable NetworkManager before using vsnm, as NetworkManager may override the changed performed by vsnm.
.SH OPTIONS
The vsnm does not take any options
.SH SEE ALSO
iwconfig(8), wpa_passphrase(8), dhclient(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Diogo Oliveira de Melo (dmelo87@gmail.com)
